# The URL the site will be built for
base_url = "https://keyvank.github.io/russki"
theme = "still"
compile_sass = true
build_search_index = false
title = "Мой блог!"
description = "Для практики русского языка!"
author = "Кейван"
default_language = "ru"

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
still_date_format = "%Y-%m-%d"
still_show_author = true